name: Pull Request Validation
on:
  pull_request:
    branches:
      - main
env:
  VERSION: 2.91.6
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
  jest:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run test
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          text: hello world
          max_characters: 9
          string_to_append: '...'
      - name: Verify Output
        run: |
          if [ "${{ steps.test-action.outputs.text }}" = "hello ..." ]; then
            echo "Output matches expected value."
          else
            echo "::error::Output mismatch: expected 'hello ...', got '${{ steps.test-action.outputs.text }}'"
            exit 1
          fi
